name: container-unit-test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the images
        run : docker-compose up -d
      - name: Test manage
        run : docker-compose exec manage /bin/sh /app/entry.sh
      - name: Test comp
        run : docker-compose exec comp /bin/sh /app/entry.sh